# Generated by Django 4.2.11 on 2024-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaigns_name', models.CharField(max_length=50)),
                ('campaigns_describre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
