# Generated by Django 4.2.11 on 2024-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leads_in',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_name', models.CharField(max_length=50)),
                ('lead_number', models.CharField(max_length=100)),
                ('id_campaign', models.IntegerField(max_length=100, null=True)),
                ('send_status', models.CharField(max_length=100, null=True)),
                ('send_timestamp', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
