# Generated by Django 4.2.11 on 2024-03-28 19:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0002_leads_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads_in",
            name="send_status",
            field=models.CharField(max_length=255),
        ),
    ]
