# Generated by Django 4.2.11 on 2024-03-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0003_auto_20240328_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='enabled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leads_in',
            name='id_campaign',
            field=models.IntegerField(null=True),
        ),
    ]
