# Generated by Django 4.2.11 on 2024-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0004_campaigns_enabled_alter_leads_in_id_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(null=True)),
                ('contract_id', models.IntegerField(null=True)),
                ('count_total', models.BigIntegerField(null=True)),
                ('value_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_name', models.CharField(max_length=150)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limit', models.IntegerField(null=True)),
                ('enabled', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('cpf', models.BigIntegerField(null=True)),
                ('cnpj', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('number_address', models.IntegerField(null=True)),
                ('zip_code', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('contract_id', models.IntegerField(null=True)),
                ('enabled', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='instances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('id_user', models.IntegerField(null=True)),
                ('id_customer', models.IntegerField(null=True)),
                ('enabled', models.IntegerField(null=True)),
                ('limit', models.IntegerField(null=True)),
                ('contract_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leads_in',
            name='send_status',
            field=models.CharField(max_length=100),
        ),
    ]
