# Generated by Django 4.2.11 on 2024-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0005_bill_customers_contracts_customers_instances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='messagens_campaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(null=True)),
                ('campaign_id', models.IntegerField(null=True)),
                ('instance_id', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('message_description', models.CharField(max_length=200, null=True)),
                ('media_url', models.CharField(max_length=255, null=True)),
                ('media_type', models.CharField(max_length=50, null=True)),
                ('media_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
