# Generated by Django 4.2.11 on 2024-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0006_messagens_campaigns'),
    ]

    operations = [
        migrations.AddField(
        model_name='customers',
        name='users_id',
        field=models.CharField(max_length=255)
        ),
    ]
