# Generated by Django 4.2.11 on 2024-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0007_auto_20240401_1217'),
    ]

    operations = [
        migrations.AddField(
        model_name='campaigns',
        name='customer_id',
        field=models.IntegerField(null=True)
        ),
    ]
