# Generated by Django 4.2.11 on 2024-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0008_auto_20240401_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='instance_id',
            field=models.IntegerField(null=True)
        ),

        migrations.AlterField(
            model_name="leads_in",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name="instances",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name="messagens_campaigns",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, auto_now=True),
        ),
    ]
