# Generated by Django 4.2.11 on 2024-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0009_auto_20240408_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name="messagens_campaigns",
            name='time_msg',
            field=models.IntegerField(null=True)
        ),
    ]
