# Generated by Django 4.2.11 on 2024-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0010_auto_20240414_1316'),
    ]

    operations = [
        migrations.AlterField(
        model_name='messagens_campaigns',
        name='message',
        field=models.TextField(blank=True, null=True),
        ),
    ]
