# Generated by Django 4.2.21 on 2025-06-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeut', '0011_auto_20240418_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_frames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.IntegerField(null=True)),
                ('message_description', models.CharField(max_length=200, null=True)),
                ('days_allowed', models.CharField(help_text='List days alloweds (ex: 0,1,2,3,4)', max_length=20)),
                ('hour_begin', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='users_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instances',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leads_in',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leads_in',
            name='send_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagens_campaigns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagens_campaigns',
            name='message',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255, null=True),
        ),
    ]
